# Exercícios de revisão — Upload de arquivo, Pandas e NumPy

Nesta atividade, você vai usar a planilha **`base_exercicios_alunos_pandas.xlsx`** para praticar leitura de arquivo, exploração de dados, filtros, tratamento simples e uma introdução ao **NumPy**.

> Professor: você pode pedir que os alunos resolvam primeiro sozinhos e depois fazer a correção em sala.

## 1. Importando as bibliotecas

Use esta célula para importar as bibliotecas necessárias.

In [6]:
import pandas as pd
import numpy as np

## 2. Carregando o arquivo

Se estiver no **Google Colab**, primeiro envie a planilha.

Se estiver no **Jupyter Notebook**, basta garantir que o arquivo está na mesma pasta do notebook.

In [7]:
# Se estiver no Google Colab, descomente estas linhas:
# from google.colab import files
# uploaded = files.upload()

df = pd.read_excel("base_exercicios_alunos_pandas.xlsx")
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

## 3. Conhecendo a base

### Exercício 1
Mostre as **5 primeiras linhas** da base.

### Exercício 2
Mostre as **5 últimas linhas** da base.

### Exercício 3
Descubra:
- quantidade de linhas e colunas
- nomes das colunas
- tipos de dados

In [9]:
# Resolva aqui
df.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

In [10]:
df.tail()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [11]:
df.shape

(30, 15)

In [12]:
df.columns

Index(['id_aluno', 'nome', 'idade', 'turma', 'curso', 'nota1', 'nota2',
       'faltas', 'cidade', 'uf', 'data_matricula', 'mensalidade', 'bolsista',
       'email', 'status'],
      dtype='object')

In [13]:
df.dtypes

id_aluno            int64
nome               object
idade             float64
turma              object
curso              object
nota1             float64
nota2             float64
faltas            float64
cidade             object
uf                 object
data_matricula     object
mensalidade       float64
bolsista           object
email              object
status             object
dtype: object

## 4. Seleção de colunas

### Exercício 4
Mostre apenas as colunas:
- `nome`
- `curso`
- `turma`
- `nota1`

### Exercício 5
Crie um novo DataFrame chamado `df_notas` contendo:
- `nome`
- `nota1`
- `nota2`
- `faltas`

In [14]:
# Resolva aqui
df[['nome', 'curso', 'turma', 'nota1']]

              nome            curso turma  nota1
0        Ana Clara               IA     A    8.5
1       Bruno Lima  Desenvolvimento     A    6.0
2      Carla Souza               IA     B    9.2
3      Diego Alves            Dados     B    5.5
4     Eduarda Melo            Dados     A    7.8
5     Felipe Rocha               IA     C    4.0
6   Gabriela Nunes  Desenvolvimento     C    8.0
7   Henrique Silva               IA     A    NaN
8    Isabela Costa            Dados     B    9.5
9       João Pedro  Desenvolvimento     A    6.7
10      Karen Dias            Dados     B    7.0
11     Lucas Matos               IA     C    3.5
12    Mariana Reis            Dados     A    8.8
13   Nicolas Prado  Desenvolvimento     B    5.9
14  Olivia Martins               IA     C   10.0
15     Paulo Vitor            Dados     A    6.3
16   Quezia Araújo               IA     B    7.4
17    Rafael Gomes  Desenvolvimento     C    4.8
18   Sara Teixeira            Dados     A    7.9
19   Thiago Mendes               IA     C    5.0
20   Ursula Ferraz            Dados     B    8.1
21  Vinicius Lopes  Desenvolvimento     A    6.9
22   Wesley Castro               IA     B    2.5
23   Ximena Duarte            Dados     C    9.1
24    Yasmin Rocha               IA     A    8.3
25     Zeca Barros  Desenvolvimento     C    6.1
26       Ana Clara               IA     A    8.5
27   Beatriz Moura              NaN     B    7.2
28    Caio Moreira            Dados     C    NaN
29   Daniela Pires  Desenvolvimento     B    8.4

In [15]:
df_notas = df[['nome', 'nota1', 'nota2', 'faltas']]
df_notas

              nome  nota1  nota2  faltas
0        Ana Clara    8.5    9.0     2.0
1       Bruno Lima    6.0    7.5     5.0
2      Carla Souza    9.2    NaN     1.0
3      Diego Alves    5.5    6.0     8.0
4     Eduarda Melo    7.8    8.1     NaN
5     Felipe Rocha    4.0    5.5    12.0
6   Gabriela Nunes    8.0    8.8     0.0
7   Henrique Silva    NaN    7.9     3.0
8    Isabela Costa    9.5    9.7     1.0
9       João Pedro    6.7    6.2     4.0
10      Karen Dias    7.0    7.0     6.0
11     Lucas Matos    3.5    4.5    15.0
12    Mariana Reis    8.8    9.1     2.0
13   Nicolas Prado    5.9    6.8     7.0
14  Olivia Martins   10.0    9.8     0.0
15     Paulo Vitor    6.3    5.9     9.0
16   Quezia Araújo    7.4    8.2     2.0
17    Rafael Gomes    4.8    NaN    11.0
18   Sara Teixeira    7.9    8.0     3.0
19   Thiago Mendes    5.0    5.2    10.0
20   Ursula Ferraz    8.1    8.3     1.0
21  Vinicius Lopes    6.9    7.1     5.0
22   Wesley Castro    2.5    3.0    18.0
23   Ximena Duarte    9.1    9.0     0.0
24    Yasmin Rocha    8.3    8.7     2.0
25     Zeca Barros    6.1    5.8    14.0
26       Ana Clara    8.5    9.0     2.0
27   Beatriz Moura    7.2    7.6     4.0
28    Caio Moreira    NaN    NaN     NaN
29   Daniela Pires    8.4    8.9     1.0

## 5. Filtros

### Exercício 6
Filtre apenas os alunos do curso **IA**.

### Exercício 7
Filtre apenas os alunos com `nota1` maior ou igual a **7**.

### Exercício 8
Filtre apenas os alunos da turma **B** e do curso **Dados**.

### Exercício 9
Filtre os alunos com mais de **5 faltas**.

In [16]:
# Resolva aqui
import pandas as pd
df = pd.read_excel('base_exercicios_alunos_pandas.xlsx')

In [17]:
df_ia = df[df['curso'] == 'IA']
df_ia

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo

In [18]:
df_nota1_7 = df[df['nota1'] >= 7]
df_nota1_7

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [19]:
df_b_dados = df[(df['turma'] == 'B') & (df['curso'] == 'Dados')]
df_b_dados

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo

In [20]:
df_faltas = df[df['faltas'] > 5]
df_faltas

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco

## 6. Valores nulos

### Exercício 10
Verifique quantos valores nulos existem em cada coluna.

### Exercício 11
Mostre apenas as linhas onde a coluna `idade` está nula.

### Exercício 12
Preencha os valores nulos de `nota1` com a média da coluna `nota1`.

In [21]:
# Resolva aqui
df.isna().sum()

id_aluno          0
nome              0
idade             2
turma             0
curso             1
nota1             2
nota2             3
faltas            2
cidade            1
uf                1
data_matricula    0
mensalidade       1
bolsista          1
email             2
status            0
dtype: int64

In [22]:
df[df['idade'].isna()]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo

In [23]:
media_nota1 = df['nota1'].mean()

df['nota1'] = df['nota1'].fillna(media_nota1)

## 7. Tratamento de texto e padronização

### Exercício 13
Padronize a coluna `bolsista` para ficar apenas com:
- `Sim`
- `Não`

Dica: existem valores como `SIM`, `sim`, `Nao`.

### Exercício 14
Padronize a coluna `uf` para letras maiúsculas.

### Exercício 15
Padronize a coluna `cidade` no formato título.
Exemplo:
- `brasília` → `Brasília`

In [24]:
# Resolva aqui
df['bolsista'] = (
    df['bolsista']
    .astype(str)
    .str.strip()
    .str.lower()
    .replace({
        'sim': 'Sim',
        'não': 'Não',
        'nao': 'Não'
    }))

In [25]:
df['uf'] = df['uf'].astype(str).str.upper()

In [26]:
df['cidade'] = df['cidade'].astype(str).str.title()

## 8. Criando novas colunas

### Exercício 16
Crie uma coluna chamada `media` com a média entre `nota1` e `nota2`.

### Exercício 17
Crie uma coluna chamada `aprovado`:
- `True` para média maior ou igual a **7**
- `False` caso contrário

### Exercício 18
Crie uma coluna chamada `situacao_faltas`:
- `Alto risco` para mais de 10 faltas
- `Atenção` para 6 a 10 faltas
- `Ok` para até 5 faltas

In [27]:
# Resolva aqui
df['media'] = (df['nota1'] + df['nota2']) / 2

In [28]:
df['aprovado'] = df['media'] >= 7

In [29]:
df['situacao_faltas'] = 'Ok'

df.loc[df['faltas'] > 5, 'situacao_faltas'] = 'Atenção'
df.loc[df['faltas'] > 10, 'situacao_faltas'] = 'Alto risco'

## 9. Ordenação, contagem e agrupamento

### Exercício 19
Ordene os alunos pela coluna `media`, do maior para o menor.

### Exercício 20
Conte quantos alunos existem em cada curso.

### Exercício 21
Mostre a média de `nota1` por curso.

### Exercício 22
Mostre a média de faltas por turma.

In [30]:
# Resolva aqui
import pandas as pd

df = pd.read_excel('base_exercicios_alunos_pandas.xlsx')

# garantir que nota1/nota2 sejam numéricas
df['nota1'] = pd.to_numeric(df['nota1'], errors='coerce')
df['nota2'] = pd.to_numeric(df['nota2'], errors='coerce')

# criar media
df['media'] = (df['nota1'] + df['nota2']) / 2

# ordenar do maior para o menor
df_ordenado = df.sort_values(by='media', ascending=False)
df_ordenado

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.90
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.60
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.05
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.95
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo,8.65
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo,8.50
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo,8.40
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo,8.20
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo,7.95
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo,7.95
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo,7.80
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo,7.40
21,22,Vinicius Lopes,19.0,A,Desenvolvimento,6.9,7.1,5.0,Goiânia,GO,2025-02-20,920.0,Não,vinicius.lopes@email.com,Ativo,7.00
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo,7.00
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo,6.75
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco,6.35
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco,6.10
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco,5.95
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco,5.75
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco,5.10
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo,4.75
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo,2.75
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo,NaN
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo,NaN
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo,NaN
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,NaN

In [31]:
df['curso'].value_counts(dropna=False)

curso
IA                 11
Dados              10
Desenvolvimento     8
NaN                 1
Name: count, dtype: int64

In [32]:
df['nota1'] = pd.to_numeric(df['nota1'], errors='coerce')
df.groupby('curso', dropna=False)['nota1'].mean()

curso
Dados              7.777778
Desenvolvimento    6.600000
IA                 6.690000
NaN                7.200000
Name: nota1, dtype: float64

In [33]:
df['faltas'] = pd.to_numeric(df['faltas'], errors='coerce')
df.groupby('turma', dropna=False)['faltas'].mean()

turma
A    3.70
B    4.90
C    7.75
Name: faltas, dtype: float64

## 10. Duplicatas e qualidade dos dados

### Exercício 23
Verifique se existem linhas duplicadas.

### Exercício 24
Remova as duplicatas e salve em um novo DataFrame chamado `df_limpo`.

### Exercício 25
Mostre os registros com emails possivelmente inválidos.
Dica: procure emails sem `@` ou sem `.com`.

In [34]:
# Resolva aqui
df.duplicated().sum()

np.int64(0)

In [35]:
df_limpo = df.drop_duplicates()

In [36]:
emails_invalidos = df[
    (~df['email'].astype(str).str.contains('@')) |
    (~df['email'].astype(str).str.contains('.com'))
]

emails_invalidos

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media
9,10,João Pedro,19.0,A,Desenvolvimento,6.7,6.2,4.0,Aparecida de Goiânia,GO,2025-02-13,920.0,Não,joao.pedro@email,Risco,6.45
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo,4.00
28,29,Caio Moreira,19.0,C,Dados,NaN,NaN,NaN,NaN,NaN,2025-02-22,780.0,NaN,NaN,Ativo,NaN

## 11. Salvando um novo arquivo

### Exercício 26
Salve o DataFrame tratado em um novo arquivo Excel chamado:
`base_tratada_alunos.xlsx`

In [37]:
# Resolva aqui
df_limpo.to_excel('base_tratada_alunos.xlsx', index=False)

## 12. Introdução ao NumPy

### Exercício 27
Crie um array NumPy com os valores da coluna `nota1`, removendo os nulos.

### Exercício 28
Com esse array, calcule:
- média
- maior valor
- menor valor
- soma

### Exercício 29
Some **1 ponto** em todas as notas do array.

### Exercício 30
Mostre apenas as notas maiores que **7** usando NumPy.

In [38]:
# Resolva aqui
import numpy as np

notas_array = df['nota1'].dropna().to_numpy()
notas_array

array([ 8.5,  6. ,  9.2,  5.5,  7.8,  4. ,  8. ,  9.5,  6.7,  7. ,  3.5,
        8.8,  5.9, 10. ,  6.3,  7.4,  4.8,  7.9,  5. ,  8.1,  6.9,  2.5,
        9.1,  8.3,  6.1,  8.5,  7.2,  8.4])

In [39]:
media = np.mean(notas_array)
maior = np.max(notas_array)
menor = np.min(notas_array)
soma = np.sum(notas_array)

media, maior, menor, soma

(np.float64(7.032142857142857),
 np.float64(10.0),
 np.float64(2.5),
 np.float64(196.89999999999998))

In [40]:
notas_ajustadas = notas_array + 1
notas_ajustadas

array([ 9.5,  7. , 10.2,  6.5,  8.8,  5. ,  9. , 10.5,  7.7,  8. ,  4.5,
        9.8,  6.9, 11. ,  7.3,  8.4,  5.8,  8.9,  6. ,  9.1,  7.9,  3.5,
       10.1,  9.3,  7.1,  9.5,  8.2,  9.4])

In [41]:
notas_maiores_7 = notas_ajustadas[notas_ajustadas > 7]
notas_maiores_7

array([ 9.5, 10.2,  8.8,  9. , 10.5,  7.7,  8. ,  9.8, 11. ,  7.3,  8.4,
        8.9,  9.1,  7.9, 10.1,  9.3,  7.1,  9.5,  8.2,  9.4])

## 13. Desafio final

### Exercício 31 — Desafio
Monte uma análise final respondendo:

1. Quantos alunos há em cada curso?
2. Qual curso tem a maior média de `nota1`?
3. Quantos alunos têm mais de 10 faltas?
4. Quantos alunos são bolsistas?
5. Há dados faltando? Em quais colunas?
6. Há duplicatas?
7. Gere um DataFrame final apenas com:
   - `nome`
   - `curso`
   - `media`
   - `aprovado`

Depois, ordene esse DataFrame pela `media` em ordem decrescente.

In [43]:
# Resolva aqui
import pandas as pd

df = pd.read_excel('base_exercicios_alunos_pandas.xlsx')

# garantir tipos numéricos
df['nota1'] = pd.to_numeric(df['nota1'], errors='coerce')
df['nota2'] = pd.to_numeric(df['nota2'], errors='coerce')
df['faltas'] = pd.to_numeric(df['faltas'], errors='coerce')

# criar media e aprovado (caso ainda não existam)
df['media'] = (df['nota1'] + df['nota2']) / 2
df['aprovado'] = df['media'] >= 7

In [44]:
alunos_por_curso = df['curso'].value_counts()
alunos_por_curso

curso
IA                 11
Dados              10
Desenvolvimento     8
Name: count, dtype: int64

In [45]:
media_nota1_por_curso = df.groupby('curso')['nota1'].mean()
media_nota1_por_curso

curso
Dados              7.777778
Desenvolvimento    6.600000
IA                 6.690000
Name: nota1, dtype: float64

## 14. Espaço para correção

Professor: aqui você pode ir resolvendo os exercícios em sala após os alunos tentarem.

In [ ]:
# Correção do professor